// Mock data for green coffee beans export catalog

export const coffeeProducts = [
  {
    id: 1,
    name: "Arabica Gayo Green Beans",
    nameId: "Green Bean Arabica Gayo",
    origin: "Aceh, Indonesia",
    originId: "Aceh, Indonesia",
    grade: "Grade 1 (Specialty)",
    process: "Wet Hulled (Giling Basah)",
    processId: "Giling Basah",
    flavor: "Earthy, Herbal, Spicy, Full Body",
    flavorId: "Earthy, Herbal, Rempah, Body Penuh",
    altitude: "1200-1600 masl",
    // Green Bean Technical Specifications
    screenSize: "Screen 17-18 (85%), Screen 15-16 (15%)",
    screenSizeId: "Screen 17-18 (85%), Screen 15-16 (15%)",
    defects: "Max 11 defects per 300g (Grade 1)",
    defectsId: "Maks 11 cacat per 300g (Grade 1)",
    moisture: "12-13%",
    waterActivity: "0.55-0.65 aw",
    density: "0.68-0.72 g/ml",
    beanColor: "Bluish Green",
    beanColorId: "Hijau Kebiruan",
    cupping: "83-86 (Specialty Grade)",
    cuppingId: "83-86 (Grade Spesial)",
    certification: "Organic, Fair Trade, Rainforest Alliance",
    certificationId: "Organik, Fair Trade, Rainforest Alliance",
    packaging: "60kg Jute/GrainPro bags",
    packagingId: "Karung Jute/GrainPro 60kg",
    minOrder: "1 Container (300 bags / 18 tons)",
    minOrderId: "1 Kontainer (300 karung / 18 ton)",
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80"
  },
  {
    id: 2,
    name: "Arabica Toraja Green Beans",
    nameId: "Green Bean Arabica Toraja",
    origin: "Sulawesi, Indonesia",
    originId: "Sulawesi, Indonesia",
    grade: "Grade 1 (Specialty)",
    process: "Wet Process (Fully Washed)",
    processId: "Proses Basah (Full Washed)",
    flavor: "Chocolate, Caramel, Dark Fruit, Low Acidity",
    flavorId: "Cokelat, Karamel, Buah Gelap, Asam Rendah",
    altitude: "1400-1800 masl",
    screenSize: "Screen 18-19 (90%), Screen 17 (10%)",
    screenSizeId: "Screen 18-19 (90%), Screen 17 (10%)",
    defects: "Max 8 defects per 300g (Grade 1)",
    defectsId: "Maks 8 cacat per 300g (Grade 1)",
    moisture: "11-12.5%",
    waterActivity: "0.50-0.60 aw",
    density: "0.70-0.75 g/ml",
    beanColor: "Blue Green",
    beanColorId: "Hijau Biru",
    cupping: "84-87 (Specialty Grade)",
    cuppingId: "84-87 (Grade Spesial)",
    certification: "Rainforest Alliance, Geographic Indication",
    certificationId: "Rainforest Alliance, Indikasi Geografis",
    packaging: "60kg Jute/GrainPro bags",
    packagingId: "Karung Jute/GrainPro 60kg",
    minOrder: "1 Container (300 bags / 18 tons)",
    minOrderId: "1 Kontainer (300 karung / 18 ton)",
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=800&q=80"
  },
  {
    id: 3,
    name: "Arabica Java Ijen Green Beans",
    nameId: "Green Bean Arabica Java Ijen",
    origin: "East Java, Indonesia",
    originId: "Jawa Timur, Indonesia",
    grade: "Grade 1 (Specialty)",
    process: "Natural Process (Sun Dried)",
    processId: "Proses Natural (Penjemuran)",
    flavor: "Fruity, Floral, Wine-like, Bright Acidity",
    flavorId: "Fruity, Floral, Wine, Asam Cerah",
    altitude: "1100-1500 masl",
    screenSize: "Screen 17-18 (80%), Screen 16 (20%)",
    screenSizeId: "Screen 17-18 (80%), Screen 16 (20%)",
    defects: "Max 10 defects per 300g (Grade 1)",
    defectsId: "Maks 10 cacat per 300g (Grade 1)",
    moisture: "11.5-12.5%",
    waterActivity: "0.52-0.62 aw",
    density: "0.69-0.73 g/ml",
    beanColor: "Green with slight yellow tint",
    beanColorId: "Hijau dengan sedikit kuning",
    cupping: "83-85 (Specialty Grade)",
    cuppingId: "83-85 (Grade Spesial)",
    certification: "UTZ Certified, 4C",
    certificationId: "Bersertifikat UTZ, 4C",
    packaging: "60kg Jute/GrainPro bags",
    packagingId: "Karung Jute/GrainPro 60kg",
    minOrder: "1 Container (300 bags / 18 tons)",
    minOrderId: "1 Kontainer (300 karung / 18 ton)",
    image: "https://images.unsplash.com/photo-1511537190424-bbbab87ac5eb?w=800&q=80"
  },
  {
    id: 4,
    name: "Robusta Lampung Green Beans",
    nameId: "Green Bean Robusta Lampung",
    origin: "Lampung, Indonesia",
    originId: "Lampung, Indonesia",
    grade: "Grade 1 (WP - Washed Process)",
    process: "Wet Process",
    processId: "Proses Basah",
    flavor: "Bold, Strong, Nutty, Earthy, High Caffeine",
    flavorId: "Kuat, Tegas, Kacang, Earthy, Kafein Tinggi",
    altitude: "600-1200 masl",
    screenSize: "Screen 16-18 (90%), Screen 13-15 (10%)",
    screenSizeId: "Screen 16-18 (90%), Screen 13-15 (10%)",
    defects: "Max 45 defects per 500g (Grade 1 Robusta)",
    defectsId: "Maks 45 cacat per 500g (Grade 1 Robusta)",
    moisture: "12-13%",
    waterActivity: "0.55-0.65 aw",
    density: "0.65-0.70 g/ml",
    beanColor: "Pale Green to Brown Green",
    beanColorId: "Hijau Pucat hingga Hijau Cokelat",
    cupping: "80-82 (Fine Robusta)",
    cuppingId: "80-82 (Fine Robusta)",
    certification: "4C Certified, Rainforest Alliance",
    certificationId: "Bersertifikat 4C, Rainforest Alliance",
    packaging: "60kg Jute bags",
    packagingId: "Karung Jute 60kg",
    minOrder: "1 Container (300 bags / 18 tons)",
    minOrderId: "1 Kontainer (300 karung / 18 ton)",
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&q=80"
  },
  {
    id: 5,
    name: "Arabica Bali Kintamani Green Beans",
    nameId: "Green Bean Arabica Bali Kintamani",
    origin: "Bali, Indonesia",
    originId: "Bali, Indonesia",
    grade: "Grade 1 (Specialty)",
    process: "Wet Process (Fully Washed)",
    processId: "Proses Basah (Full Washed)",
    flavor: "Citrus, Spicy, Floral, Medium Body",
    flavorId: "Citrus, Rempah, Floral, Body Sedang",
    altitude: "900-1500 masl",
    screenSize: "Screen 17-18 (85%), Screen 16 (15%)",
    screenSizeId: "Screen 17-18 (85%), Screen 16 (15%)",
    defects: "Max 9 defects per 300g (Grade 1)",
    defectsId: "Maks 9 cacat per 300g (Grade 1)",
    moisture: "11-12%",
    waterActivity: "0.50-0.60 aw",
    density: "0.69-0.73 g/ml",
    beanColor: "Bluish Green",
    beanColorId: "Hijau Kebiruan",
    cupping: "84-86 (Specialty Grade)",
    cuppingId: "84-86 (Grade Spesial)",
    certification: "Geographic Indication (IGP), Organic",
    certificationId: "Indikasi Geografis (IGP), Organik",
    packaging: "60kg GrainPro bags",
    packagingId: "Karung GrainPro 60kg",
    minOrder: "1 Container (300 bags / 18 tons)",
    minOrderId: "1 Kontainer (300 karung / 18 ton)",
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800&q=80"
  },
  {
    id: 6,
    name: "Arabica Flores Bajawa Green Beans",
    nameId: "Green Bean Arabica Flores Bajawa",
    origin: "Flores, Indonesia",
    originId: "Flores, Indonesia",
    grade: "Grade 1 (Specialty)",
    process: "Semi Washed (Honey Process)",
    processId: "Semi Basah (Honey Process)",
    flavor: "Sweet, Chocolate, Brown Sugar, Balanced",
    flavorId: "Manis, Cokelat, Gula Merah, Seimbang",
    altitude: "1200-1700 masl",
    screenSize: "Screen 17-18 (90%), Screen 16 (10%)",
    screenSizeId: "Screen 17-18 (90%), Screen 16 (10%)",
    defects: "Max 8 defects per 300g (Grade 1)",
    defectsId: "Maks 8 cacat per 300g (Grade 1)",
    moisture: "11.5-12.5%",
    waterActivity: "0.52-0.62 aw",
    density: "0.70-0.74 g/ml",
    beanColor: "Green with honey tint",
    beanColorId: "Hijau dengan warna madu",
    cupping: "84-87 (Specialty Grade)",
    cuppingId: "84-87 (Grade Spesial)",
    certification: "Organic, Direct Trade",
    certificationId: "Organik, Direct Trade",
    packaging: "60kg GrainPro bags",
    packagingId: "Karung GrainPro 60kg",
    minOrder: "1 Container (300 bags / 18 tons)",
    minOrderId: "1 Kontainer (300 karung / 18 ton)",
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=800&q=80"
  }
];

export const companyInfo = {
  name: "Indonesian Green Coffee Beans Export",
  nameId: "Ekspor Green Bean Kopi Indonesia",
  tagline: "Premium Green Coffee Beans Direct from Indonesian Highlands",
  taglineId: "Biji Kopi Mentah Premium Langsung dari Dataran Tinggi Indonesia",
  description: "We are specialized green coffee beans exporters supplying premium unroasted Indonesian specialty coffee to international roasters and importers. With direct farm partnerships across the archipelago, we provide fully traceable, quality-certified green beans with complete technical specifications for your roasting needs.",
  descriptionId: "Kami adalah eksportir biji kopi mentah (green bean) khusus yang memasok kopi spesial Indonesia yang belum disangrai kepada roaster dan importir internasional. Dengan kemitraan langsung dengan petani di seluruh kepulauan, kami menyediakan green bean yang dapat dilacak sepenuhnya, bersertifikat kualitas dengan spesifikasi teknis lengkap untuk kebutuhan roasting Anda.",
  email: "petensarman13@gmail.com",
  phone: "+62 895-6033-18877",
  address: "Medan, Indonesia",
  whatsapp: "62895603318877"
};